// lib/cms/agents/prospecting-agent.test.ts
//
// Unit tests for the Prospecting_Agent (S7 task 5.1).
//
// Validates: Requirements 10.2, 10.3, 10.4, 10.5, 10.6, 8.1.
//  - the agent is granted EXACTLY the navigator's catalog tools (the market
//    reads, search/enrich, the Target write, and the promotion handoff) and is
//    NOT granted `draft_outreach` or the human-gated `send_outreach` (8.1);
//  - it declares the `premium` tier routed through the `doe` CF gateway;
//  - entry-mode resolution picks the property-led hero path for a brief and the
//    ICP-led inverse for a bare filter (10.2, 10.5);
//  - a brief-led turn extracts a validated Buyer_Hypothesis and emits the
//    editable `prospecting.hypothesis.proposed` proposal (10.6), while an
//    ICP-led turn requests no structured hypothesis and emits nothing;
//  - the container-tier guard refuses a serverless invocation.
//
// The model gateway is never hit: the turn runner is exercised through its
// `agent` test seam. The event bus is stubbed so no database is required.

import { describe, it, expect, vi, beforeEach } from "vitest";

// Stub the event bus so `publishHypothesisProposed` records a call without a DB.
const publishEvent = vi.fn().mockResolvedValue(undefined);
vi.mock("@/lib/cms/realtime/events", () => ({
  publishEvent: (...args: unknown[]) => publishEvent(...args),
}));

import {
  PROSPECTING_AGENT_ACTOR,
  PROSPECTING_CAPABILITY_NAMES,
  loadProspectingCapabilities,
} from "@/lib/cms/ai/tools/prospecting-capabilities";
import { bindCatalog } from "@/lib/cms/agents/binding";
import {
  PROSPECTING_AGENT_MODEL,
  PROSPECTING_AGENT_MODEL_TIER,
  PROSPECTING_AGENT_NAME,
  PROSPECTING_AGENT_TOOL_NAMES,
  ProspectingAgentTierError,
  assertProspectingContainerTier,
  extractHypothesis,
  prospectingAgent,
  resolveProspectingEntry,
  runProspectingAgentTurn,
  type ProspectingAgentLike,
} from "@/lib/cms/agents/prospecting-agent";
import { MODEL_TIERS } from "@/lib/cms/agents/gateway";
import type { BuyerHypothesis } from "@/lib/cms/prospecting/hypothesis";
import type { ProspectingBrief } from "@/lib/cms/prospecting/brief";

// ── Fixtures ──────────────────────────────────────────────────────────────────

const BRIEF: ProspectingBrief = {
  spec: {
    area: "Palm Jumeirah",
    segment: "ultra_luxury",
    unitType: "villa",
    bedrooms: 4,
    priceMinAed: 30_000_000,
    priceMaxAed: 50_000_000,
    features: ["sea view", "branded"],
  },
};

const VALID_HYPOTHESIS: BuyerHypothesis = {
  segments: ["post-liquidity founders", "family offices"],
  feederMarkets: ["India", "UK"],
  titles: ["Founder", "Managing Partner"],
  wealthSignals: ["recent exit"],
  evidence: [
    {
      claim: "Comparable villas transacted around AED 42M in the last year",
      sourceTable: "market_transactions",
      asOf: "2026-01-15T00:00:00.000Z",
    },
  ],
  confidence: "medium",
};

/** A mock agent whose `generate` returns a controlled Mastra-shaped result. */
function mockAgent(
  result: unknown,
): ProspectingAgentLike & { generate: ReturnType<typeof vi.fn> } {
  return { generate: vi.fn().mockResolvedValue(result) };
}

beforeEach(() => {
  publishEvent.mockClear();
});

// ── Construction & RBAC grant (Requirement 8.1) ──────────────────────────────

describe("Prospecting_Agent construction (Requirement 8.1)", () => {
  it("is granted exactly the navigator's tools and never the outreach/send tools", () => {
    expect([...PROSPECTING_AGENT_TOOL_NAMES].sort()).toEqual(
      [
        "enrich_target",
        "find_comparables",
        "market_comps",
        "promote_target_to_lead",
        "prospect_search",
        "record_target",
      ].sort(),
    );
    // The human-gated send and the Outreach_Agent's drafting tool are excluded.
    expect(PROSPECTING_AGENT_TOOL_NAMES).not.toContain("send_outreach");
    expect(PROSPECTING_AGENT_TOOL_NAMES).not.toContain("draft_outreach");
  });

  it("only grants names that exist in the prospecting catalog", () => {
    for (const name of PROSPECTING_AGENT_TOOL_NAMES) {
      expect(PROSPECTING_CAPABILITY_NAMES).toContain(name);
    }
  });

  it("dispatches under the agent:prospecting identity on the premium tier", () => {
    expect(PROSPECTING_AGENT_ACTOR).toBe("agent:prospecting");
    expect(PROSPECTING_AGENT_MODEL_TIER).toBe("premium");
    expect(PROSPECTING_AGENT_MODEL).toBe(`doe/cf/${MODEL_TIERS.premium}`);
  });

  it("binds exactly one tool per granted name (1:1) under the prospecting identity", () => {
    // The agent's tools are generated by bindCatalog over the loaded catalog —
    // exercise that same binding directly (the Mastra Agent does not expose its
    // tool map as a plain object).
    const load = loadProspectingCapabilities();
    expect(load.ok).toBe(true);
    if (!load.ok) return;

    const bound = bindCatalog(load.catalog, [...PROSPECTING_AGENT_TOOL_NAMES], {
      agentActor: PROSPECTING_AGENT_ACTOR,
    });
    expect(Object.keys(bound).sort()).toEqual(
      [...PROSPECTING_AGENT_TOOL_NAMES].sort(),
    );
    expect(prospectingAgent.name).toBe(PROSPECTING_AGENT_NAME);
  });
});

// ── Entry-mode resolution (Requirements 10.2, 10.5) ───────────────────────────

describe("resolveProspectingEntry", () => {
  it("picks the property-led hero path when a brief is present", () => {
    expect(resolveProspectingEntry({ brief: BRIEF })).toBe("brief");
    // A brief takes precedence even if an ICP filter is also supplied.
    expect(resolveProspectingEntry({ brief: BRIEF, icp: {} })).toBe("brief");
  });

  it("picks the ICP-led inverse for a bare filter", () => {
    expect(resolveProspectingEntry({ icp: { targetType: "company" } })).toBe(
      "icp",
    );
  });

  it("falls back to a conversational turn when neither is present", () => {
    expect(resolveProspectingEntry({})).toBe("chat");
  });
});

// ── Hypothesis extraction (Requirements 10.3, 10.4) ───────────────────────────

describe("extractHypothesis", () => {
  it("returns a validated hypothesis from structured output", () => {
    expect(extractHypothesis({ object: VALID_HYPOTHESIS })).toEqual(
      VALID_HYPOTHESIS,
    );
  });

  it("returns null when there is no structured output", () => {
    expect(extractHypothesis({ text: "no object here" })).toBeNull();
    expect(extractHypothesis(null)).toBeNull();
    expect(extractHypothesis(undefined)).toBeNull();
  });

  it("returns null when the structured output fails schema validation", () => {
    // `confidence` outside the enum, evidence sourceTable not a market_* table.
    expect(
      extractHypothesis({
        object: { ...VALID_HYPOTHESIS, confidence: "certain" },
      }),
    ).toBeNull();
    expect(
      extractHypothesis({
        object: {
          ...VALID_HYPOTHESIS,
          evidence: [
            { claim: "x", sourceTable: "leads_mirror", asOf: "2026-01-01T00:00:00.000Z" },
          ],
        },
      }),
    ).toBeNull();
  });
});

// ── Container-tier guard ([container-only]) ───────────────────────────────────

describe("assertProspectingContainerTier", () => {
  it("refuses a serverless invocation", () => {
    expect(() => assertProspectingContainerTier(true)).toThrow(
      ProspectingAgentTierError,
    );
  });

  it("permits a container/worker invocation", () => {
    expect(() => assertProspectingContainerTier(false)).not.toThrow();
  });
});

// ── runProspectingAgentTurn (Requirements 10.2, 10.5, 10.6) ───────────────────

describe("runProspectingAgentTurn", () => {
  const db = {} as never; // never touched — publishEvent is stubbed

  it("brief-led: pulls comparables, proposes an editable hypothesis, emits the event", async () => {
    const agent = mockAgent({
      text: "Here are the comparables and who tends to buy them.",
      object: VALID_HYPOTHESIS,
      toolResults: [
        { payload: { toolName: "find_comparables", result: { comparables: [] } } },
      ],
    });

    const out = await runProspectingAgentTurn(
      { message: "Find buyers for this villa", brief: BRIEF },
      { agent, serverless: false, db },
    );

    expect(out.ok).toBe(true);
    if (!out.ok) return;
    expect(out.mode).toBe("brief");
    expect(out.hypothesis).toEqual(VALID_HYPOTHESIS);
    expect(out.hypothesisProposed).toBe(true);
    expect(out.toolResults).toEqual([
      { toolName: "find_comparables", result: { comparables: [] } },
    ]);

    // The editable proposal was published exactly once (Requirement 10.6).
    expect(publishEvent).toHaveBeenCalledTimes(1);
    const [, event] = publishEvent.mock.calls[0];
    expect(event.type).toBe("prospecting.hypothesis.proposed");
    expect(event.payload.hypothesis).toEqual(VALID_HYPOTHESIS);

    // A brief-led turn requests the hypothesis as structured output.
    const [, genOptions] = agent.generate.mock.calls[0];
    expect(genOptions).toHaveProperty("output");
  });

  it("brief-led without a db: returns the hypothesis but emits no event", async () => {
    const agent = mockAgent({ text: "", object: VALID_HYPOTHESIS, toolResults: [] });

    const out = await runProspectingAgentTurn(
      { message: "Find buyers", brief: BRIEF },
      { agent, serverless: false },
    );

    expect(out.ok).toBe(true);
    if (!out.ok) return;
    expect(out.hypothesis).toEqual(VALID_HYPOTHESIS);
    expect(out.hypothesisProposed).toBe(false);
    expect(publishEvent).not.toHaveBeenCalled();
  });

  it("ICP-led: skips the hypothesis, requests no structured output, emits nothing", async () => {
    const agent = mockAgent({
      text: "Searching for family offices in DIFC.",
      toolResults: [
        { payload: { toolName: "prospect_search", result: { candidates: [] } } },
      ],
    });

    const out = await runProspectingAgentTurn(
      { message: "find me family offices in DIFC", icp: { targetType: "company" } },
      { agent, serverless: false, db },
    );

    expect(out.ok).toBe(true);
    if (!out.ok) return;
    expect(out.mode).toBe("icp");
    expect(out.hypothesis).toBeNull();
    expect(out.hypothesisProposed).toBe(false);
    expect(publishEvent).not.toHaveBeenCalled();

    // No structured-output request on an ICP-led turn.
    const [, genOptions] = agent.generate.mock.calls[0];
    expect(genOptions).not.toHaveProperty("output");
  });

  it("refuses to run on the serverless tier before invoking the model", async () => {
    const agent = mockAgent({ text: "", toolResults: [] });
    await expect(
      runProspectingAgentTurn(
        { message: "hi", brief: BRIEF },
        { agent, serverless: true },
      ),
    ).rejects.toBeInstanceOf(ProspectingAgentTierError);
    expect(agent.generate).not.toHaveBeenCalled();
  });
});
